spring:
  datasource:
    url: jdbc:h2:mem:tpjaddb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
application:
  jwt:
    secretKey: PhotoAlbumApi
    tokenPrefix: Bearer
server:
  port: 8888